#!/bin/bash

python3 -m grpc_tools.protoc proto/*.proto \
  --proto_path=proto                       \
  --python_out=generated                   \
  --grpc_python_out=generated

for file in generated/*.py; do
  sed -e 's/^import \(.*\) as \(.*\)/import generated.\1 as \2/g' -i $file
done